load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "inference",
  hdrs = ["inference.h"],
  deps = [
    "//huggingface_api_cpp/inference:hf_inference",
  ],
  visibility = ["//visibility:public"],
)
